// Auto-generated by OpenLane
module alu_8bit(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input[7:0] A,
  input[7:0] B,
  input[2:0] opcode,
  output[7:0] result,
  output carry,
  output zero
);
endmodule
